package helper

var (
	// InternalServer ...
	InternalServer = "internal_server"

	// HeaderNotPresent ...
	HeaderNotPresent = "header_not_present"
	// UnexpectedSigningMethod ...
	UnexpectedSigningMethod = "unexpected_signing_method"
	// UnexpectedClaims ...
	UnexpectedClaims = "unexpected_claims"
	// ExpiredToken ...

	// Unauthorized ...
	Unauthorized = "unauthoized"

	// InvalidRole ...
	InvalidRole = "invalid_role"

	// ExpiredToken ...
	ExpiredToken = "expired_token"
	// JWT ...
	JWT = "jwt"
)
